Viweb\FaqBundle\Entity\FaqTranslation:
    type: entity
    table: null
    repositoryClass: Viweb\FaqBundle\Repository\FaqTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        answer:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
