services:
    viweb_faq.admin_menu_listener:
        class: Viweb\FaqBundle\EventListener\ConfigureAdminMenuListener
        tags:
          - { name: kernel.event_listener, event: viweb_system.menu_admin_configure, method: onMenuConfigure }
