viweb_admin_faq:
    resource: |
        alias: viweb.faq
        redirect: update
        except: ['show', 'update']
        section: admin
        templates: ViwebSystemBundle:Crud
        grid: viweb_faq
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'outline'
    type: sylius.resource

viweb_admin_faq_update:
    path: /faqs/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: viweb.controller.faq:updateAction
        _sylius:
            section: admin
            template: ViwebSystemBundle:Crud:update.html.twig
