<?php

namespace Viweb\FaqBundle\Repository;

/**
 * FaqTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
